### ISSUE TITLE
Reproducible Research

### ISSUE THREAD

**Issue by TobiasRoth** [TobiasRoth/BDAEcology#3]
We should also have a chapter on reproducible Research Using RMarkdown and Git with RStudio.

**Comment by fraenzi** [comment]
this could include a vocabulary, e.g. how to specify the figure width when using the beamer_presentation output format in rmarkdown:
- figures that are not produced by R need to have the correct size before compiling the pdf
- figures produced by R, use fig.width=5 in the r-chunk options
